### ISSUE TITLE
Too much free space when number has a period

### ISSUE THREAD

**Issue by 4Kazelot** [DakerHub/vue-digital-transform#6]
As in the title. Can anything be done about it?
![image](https://user-images.githubusercontent.com/19856602/99517250-6ff01800-298f-11eb-8bf8-070fbc9883c5.png)

**Comment by DakerHub** [comment]
I Just saw this issus, sorry.

Maybe you can use the below css.
```css
.digital-transform {
  text-align: center;
}
```
That will looks better.
